import type { Campaign, Testimonial } from "./types"

export const campaigns: Campaign[] = [
  {
    id: "clean-water-project",
    title: "Clean Water for Rural Communities",
    description: "Help provide clean drinking water to rural communities in developing countries.",
    longDescription:
      "Access to clean water is a fundamental human right, yet millions of people around the world still lack this basic necessity. This campaign aims to fund the construction of water wells and filtration systems in rural communities across developing countries. Your donation will help provide families with clean drinking water, reducing waterborne diseases and improving overall health and quality of life. We work directly with local communities to ensure sustainable solutions that will last for generations.",
    image: "https://picsum.photos/seed/water-project/600/400",
    category: "Health",
    goal: 50000,
    currentAmount: 32500,
    startDate: "2023-10-15",
    deadline: "2024-06-30",
    organizer: "Global Water Initiative",
    donors: 215,
  },
  {
    id: "education-for-all",
    title: "Education for Underprivileged Children",
    description: "Support education programs for underprivileged children in urban areas.",
    longDescription:
      "Education is the key to breaking the cycle of poverty, but many children from disadvantaged backgrounds face significant barriers to accessing quality education. This campaign funds scholarships, school supplies, and after-school programs for underprivileged children in urban areas. By supporting this initiative, you're helping to provide equal educational opportunities and a brighter future for children who need it most. Our programs have already helped hundreds of students stay in school and pursue their dreams.",
    image: "https://picsum.photos/seed/education-project/600/400",
    category: "Education",
    goal: 75000,
    currentAmount: 45000,
    startDate: "2023-09-01",
    deadline: "2024-05-15",
    organizer: "Education First Foundation",
    donors: 320,
  },
  {
    id: "wildlife-conservation",
    title: "Protect Endangered Wildlife",
    description: "Help protect endangered species and their habitats from extinction.",
    longDescription:
      "Our planet is experiencing an unprecedented rate of species extinction due to habitat loss, climate change, and human activities. This campaign supports conservation efforts to protect endangered wildlife and preserve biodiversity. Funds will be used for habitat restoration, anti-poaching initiatives, research, and community education programs. By contributing to this cause, you're helping to ensure that future generations can enjoy the rich diversity of life on Earth and maintaining the delicate balance of our ecosystems.",
    image: "https://picsum.photos/seed/wildlife-project/600/400",
    category: "Environment",
    goal: 100000,
    currentAmount: 68000,
    startDate: "2023-11-20",
    deadline: "2024-07-15",
    organizer: "Wildlife Protection Alliance",
    donors: 450,
  },
  {
    id: "disaster-relief",
    title: "Emergency Disaster Relief Fund",
    description: "Provide immediate assistance to victims of natural disasters worldwide.",
    longDescription:
      "When natural disasters strike, immediate response is crucial to save lives and provide relief to affected communities. This emergency fund enables rapid deployment of resources including food, clean water, shelter, and medical aid to disaster zones around the world. Your contribution helps us maintain readiness to respond quickly when disasters occur, ensuring that help reaches those who need it most during their most vulnerable moments. We work with local partners to ensure culturally appropriate and effective aid delivery.",
    image: "https://picsum.photos/seed/disaster-relief/600/400",
    category: "Disaster Relief",
    goal: 200000,
    currentAmount: 125000,
    startDate: "2023-08-10",
    deadline: "2024-08-10",
    organizer: "Global Relief Network",
    donors: 780,
  },
  {
    id: "homeless-shelter",
    title: "Expand Community Homeless Shelter",
    description: "Help expand our local homeless shelter to serve more people in need.",
    longDescription:
      "Homelessness is a growing crisis in many communities, with shelters often operating at maximum capacity. This campaign aims to expand our community homeless shelter, adding 50 new beds and improving facilities to better serve those experiencing homelessness. The expanded shelter will also offer comprehensive support services including mental health counseling, job placement assistance, and housing navigation to help individuals transition to permanent housing. Your support provides not just a safe place to sleep, but a pathway to stability and self-sufficiency.",
    image: "https://picsum.photos/seed/homeless-shelter/600/400",
    category: "Housing",
    goal: 150000,
    currentAmount: 87500,
    startDate: "2023-12-01",
    deadline: "2024-05-01",
    organizer: "Community Housing Coalition",
    donors: 340,
  },
  {
    id: "medical-research",
    title: "Breakthrough Cancer Research",
    description: "Fund innovative research for more effective cancer treatments.",
    longDescription:
      "Despite significant advances in cancer treatment, there is still much work to be done to improve outcomes for patients. This campaign supports cutting-edge research into novel cancer therapies that show promise for treating aggressive and currently incurable forms of cancer. The research team is exploring innovative approaches that could lead to breakthroughs in treatment effectiveness while reducing side effects. Your donation directly funds laboratory work, clinical trials, and the development of new therapeutic approaches that could save countless lives in the future.",
    image: "https://picsum.photos/seed/cancer-research/600/400",
    category: "Health",
    goal: 500000,
    currentAmount: 275000,
    startDate: "2023-07-15",
    deadline: "2024-07-15",
    organizer: "Medical Research Foundation",
    donors: 1250,
  },
  {
    id: "animal-shelter",
    title: "Local Animal Shelter Renovation",
    description: "Help renovate our animal shelter to provide better care for abandoned pets.",
    longDescription:
      "Our local animal shelter has been serving the community for over 20 years, but the facilities are now outdated and in urgent need of renovation. This campaign will fund essential upgrades including improved ventilation systems, modernized kennels, a new veterinary care room, and outdoor exercise areas. These improvements will significantly enhance the quality of life for animals in our care while they await their forever homes. The renovated shelter will also be more energy-efficient, reducing operating costs and environmental impact over the long term.",
    image: "https://picsum.photos/seed/animal-shelter/600/400",
    category: "Animals",
    goal: 75000,
    currentAmount: 42000,
    startDate: "2023-10-01",
    deadline: "2024-04-15",
    organizer: "Paws & Claws Rescue",
    donors: 310,
  },
  {
    id: "community-garden",
    title: "Urban Community Garden Project",
    description: "Transform vacant lots into productive community gardens in urban neighborhoods.",
    longDescription:
      "Urban food deserts are a significant problem in many cities, with limited access to fresh, nutritious food. This community garden project aims to convert vacant lots into productive green spaces where residents can grow their own fruits and vegetables. The gardens will serve as both a source of healthy food and educational spaces where community members can learn about nutrition, sustainable agriculture, and environmental stewardship. Your support will fund soil remediation, irrigation systems, tools, seeds, and educational programs.",
    image: "https://picsum.photos/seed/community-garden/600/400",
    category: "Environment",
    goal: 35000,
    currentAmount: 18500,
    startDate: "2023-11-15",
    deadline: "2024-05-30",
    organizer: "Urban Greening Initiative",
    donors: 175,
  },
]

export const testimonials: Testimonial[] = [
  {
    name: "Sarah Johnson",
    title: "Regular Donor",
    quote:
      "I've been donating through GiveHope for over a year now. The transparency and impact reports make me confident my contributions are making a real difference.",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    rating: 5,
  },
  {
    name: "Michael Chen",
    title: "Campaign Organizer",
    quote:
      "As someone who started a campaign on GiveHope, I was impressed by how easy the platform made it to reach our funding goal. The support team was incredibly helpful.",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    rating: 5,
  },
  {
    name: "Aisha Patel",
    title: "Monthly Supporter",
    quote:
      "What I love about GiveHope is the variety of causes I can support. From environmental projects to education initiatives, I can direct my donations where they're needed most.",
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    rating: 4,
  },
]
